###################################################################
# Created Date: 10.02.2023 06:57
# Author: Fabrice Krebs
# -----
# Last Modified: 14.02.2023 09:47
# Modified By: Fabrice Krebs
###################################################################

spec:
  destination:
    server : https://10.42.6.90:443

  project: demo-argo-01

metallb:
  IPPool: 10.42.6.100-10.42.6.103
    