###################################################################
# Created Date: 08.02.2023 16:10
# Author: Fabrice Krebs
# -----
# Last Modified: 14.02.2023 08:18
# Modified By: Fabrice Krebs
###################################################################

#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: nginx
#spec:
#  entryPoints:
#    - web
#  routes:
#    - match: Host(`nginx-route.test.com`)
#      kind: Rule
#      services:
#      - kind: Service
#        name: nginx
#        port: 80