###################################################################
# Created Date: 08.02.2023 16:10
# Author: Fabrice Krebs
# -----
# Last Modified: 14.02.2023 09:39
# Modified By: Fabrice Krebs
###################################################################

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd-system
spec:
  project: {{ .Values.spec.project }}
  destination:
    namespace: metallb
    server: {{ .Values.spec.destination.server }}
  source:
    path: cluster-setup/metallb
    repoURL: https://github.com/fabricekrebs/gitops
    targetRevision: HEAD
    helm:
      parameters:
      - name: IPPool
        value: {{ .Values.metallb.IPPool }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true