apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
spec:
  addresses:
  - {{ .Values.IPPool }}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
