apiVersion: v2
name: metallb
description: Metallb configuration
type: application
version: 1.0.0
appVersion: "0.13.7"

dependencies:
  - name: metallb
    version: 0.13.7
    repository: https://metallb.github.io/metallb